### ISSUE TITLE
创建的Blob有问题，视频保存不了

### ISSUE THREAD

**Issue by hicpp** [Momo707577045/m3u8-downloader#107]
在这里创建Blob时出现异常：
const fileBlob = new Blob(fileDataList, { type: 'video/MP2T' })

创建的Blob对象有问题，点开能看到里面的异常：
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.invokeGetter (<anonymous>:3:28)
    at Vue.downloadFile (file:///Users/xxx/Downloads/m3u8-downloader-master/index.html:836:9)
    at Vue.forceDownload (file:///Users/xxx/Downloads/m3u8-downloader-master/index.html:868:14)
    at invokeWithErrorHandling (https://upyun.luckly-mjw.cn/lib/vue.js:1862:28)
    at HTMLDivElement.invoker (https://upyun.luckly-mjw.cn/lib/vue.js:2187:16)
    at original._wrapper (https://upyun.luckly-mjw.cn/lib/vue.js:7540:27)

视频保存不下来，这个是代码兼容性的问题吗？

**Comment by Momo707577045** [comment]
留一下视频地址，我本地测试看看
